let scores = Array.from({ length: 8 }, () => Math.floor(Math.random() * 71) + 30);
let highest = Math.max(...scores);
let lowest = Math.min(...scores);
let average = (scores.reduce((a, b) => a + b, 0) / scores.length).toFixed(2);
let passed = scores.filter(s => s >= 50).length;
console.log(`Scores: ${scores.join(", ")}`);
console.log(`Highest: ${highest}`);
console.log(`Lowest: ${lowest}`);
console.log(`Average: ${average}`);
console.log(`Students Passed: ${passed}/${scores.length}`);
